name: 'Service Versioning'
description: 'Per-service semantic versioning for monorepos using tag detection or auto-bumping.'
author: 'Zoltán Balogh'

branding:
  icon: 'tag'
  color: 'purple'

inputs:
  service-name:
    required: true
    description: 'The name of the service to version (e.g., AuthService)'
  version-folder:
    required: true
    description: 'The root folder where the version file will be stored (e.g., versions)'
  retry-count:
    required: false
    default: '5'
    description: 'Number of times to retry Git push operations if they fail due to race conditions'

outputs:
  version:
    description: 'The computed semantic version'
    value: ${{steps.version.outputs.version}}

runs:
  using: 'composite'
  steps:
    - id: version
      shell: bash
      run: |
        set -e
        
        VERSION_FILE="${{ inputs.version-folder }}/${{ inputs.service-name }}/VERSION"
        RETRY_COUNT="${{ inputs.retry-count }}"

        mkdir -p "$(dirname "$VERSION_FILE")"

        commit_and_push() {
          local tries=0
          until git push || [ "$tries" -ge "$RETRY_COUNT" ]; do
            tries=$((tries + 1))
            echo "Git push failed — retry $tries/$RETRY_COUNT"
            sleep 2
            git pull --rebase
          done
        
          if [ "$tries" -ge "$RETRY_COUNT" ]; then
            echo "❌ Git push failed after $RETRY_COUNT attempts."
            exit 1
          fi
        }
        
        if [[ "${GITHUB_REF}" == refs/tags/${{ inputs.service-name }}@* ]]; then
          VERSION="${GITHUB_REF#refs/tags/${{ inputs.service-name }}@}"
          echo "$VERSION" > "$VERSION_FILE"

          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add "$VERSION_FILE"
          git commit -m "chore(${{ inputs.service-name }}): set version from tag to $VERSION"
          commit_and_push
        else
          if [[ -f "$VERSION_FILE" ]]; then
            VERSION=$(cat "$VERSION_FILE")
          else
            VERSION="0.0.0"
          fi

          IFS='.' read -r MAJOR MINOR PATCH <<< "$VERSION"
          PATCH=$((PATCH + 1))
          VERSION="$MAJOR.$MINOR.$PATCH"
          echo "$VERSION" > "$VERSION_FILE"

          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add "$VERSION_FILE"
          git commit -m "chore(${{ inputs.service-name }}): bump version to $VERSION"
          commit_and_push
        fi

        echo "version=$VERSION" >> "$GITHUB_OUTPUT"